[TagsCloud]
  Enable = true
  Limit = 10
[autoCollapseToc]
  Enable = true

[Share]
  Enable = true
  AddthisId = "Your AddthisId"

[Comment]
  Enable = true
  Module = "Waline"
  LiveReId = "Your LiveReId"
  WalineSerURL = "Your WalineSerURL"

  # If Module is "Utterances",see https://utteranc.es/
  UtterancesRepo = "owner/repo"
  UtterancesTheme = "github-light"
  UtterancesTitle = "pathname"

[LeanCloud]
  AppId = "Your LCAppId"
  AppKey = "Your LCAppKey"
  ServerURL = "Your LCServer"

[Statis]
  BusuanziCounter = true
#  CNNZSiteId = "Your CNNZSiteId"
#  BaiduSiteId = "Your BaiduSiteId"
  GoogleSiteId = "UA-209130979-1"

[OnlineIM]
  Enable = false
#  DaoVoiceId = "Your DaoVoiceId"

[Others]
#  RevolverMapId = "Your RevolverMapId"